Fix slash error with AzAuth
luuxis/minecraft-java-core pull request #23
Opened 2024-05-14 19:12 UTC by Riptiaz

Use URL function to decode the URL

2024-07-11 08:18 UTC, GeekCornerGH requested changes
Haven't tested yet, here are my first thoughts.

Also when making a PR on GitHub, you should consider creating your pull request from another branch than the default one

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +    "name": "minecraft-java-core-azbetter",
I don't think you'll want to add this in the PR
```suggestion
    "name": "minecraft-java-core",
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +    "version": "3.11.0",
And I don't think you should be the one who bumps the deps
```suggestion
    "version": "3.10.4",
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +    "description": "A library starting minecraft game NW.js and Electron.js with better Azuriom support.",
Again, you'll probably want to remove this part
```suggestion
    "description": "A library starting minecraft game NW.js and Electron.js",
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +    "license": "SEE LICENSE IN LICENSE.md",
Please revert this
```suggestion
    "author": "Luuxis",
    "license": "CCANC",
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +        "url": "https://github.com/riptiaz/minecraft-java-core/issues"
```suggestion
        "url": "https://github.com/luuxis/minecraft-java-core/issues"
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +    "homepage": "https://github.com/riptiaz/minecraft-java-core#readme",
```suggestion
    "homepage": "https://github.com/luuxis/minecraft-java-core#readme",
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +        "url": "git+https://github.com/riptiaz/minecraft-java-core.git"
```suggestion
        "url": "git+https://github.com/luuxis/minecraft-java-core.git"
```

2024-07-11 08:18 UTC, GeekCornerGH commented on package.json
> +        "test": "test"
Why was this added?

2024-07-11 08:43 UTC, Riptiaz commented on package.json
> +        "test": "test"
Idk, when I run npm init it was added, you can remove I think

2024-10-21 16:20 UTC, GeekCornerGH commented
Fixed in https://github.com/luuxis/minecraft-java-core/commit/5fbb49d88f866fed9f308440d408677b026e8ba1

2024-10-21 16:20 UTC, closed without merging